#!/usr/bin/bash
delete_pyc() {
    find . -type f -name "*.pyc" -delete
}

delete_pycache() {
    find . -type d -name "__pycache__" -exec rm -rf {} +
}
is_postscript() {
    mime_type=$(file -b --mime-type "$1")
    if [[ $mime_type == "application/postscript" ]]; then
        return 0
    else
        return 1
    fi
}
delete_postscript_files() {
    local directory="$1"
    find "$directory" -maxdepth 3 -type f | while read -r file; do
        if is_postscript "$file"; then
            echo "Deleting: $file"
            rm "$file"
        fi
    done
}
clean() {
    delete_pyc
    delete_pycache
}
curr = $(date +%s)
touch .working
echo BUILD START.
echo CLEANING UP INSTALLATION [PASS 1/2]
clean
echo GENERATE PYDOC
pydoc pythinux > pythinux/man/pydoc
file_path="pythinux/man/pydoc"
if [ ! -f "$file_path" ]; then
    echo "Error: File '$file_path' does not exist."
    exit 1
fi
content=$(cat "$file_path")
new_content=$(echo "$content" | sed '/^FILE$/,/^$/d')
echo "$new_content" > "$file_path"
echo FORMAT USING BLACK
black pythinux.py -l 79
echo GENERATE LINT
echo '# This file was autogenerated using flake8.' > pythinux/man/lint
echo '# flake8 is a code linter that lists all violations of python standards.' >> pythinux/man/lint
flake8 pythinux.py --exclude E722; F405 >> pythinux/man/lint
cp pythinux/man/lint Documentation/Technical/lint.txt
rm .working
echo CLEANING UP INSTALLATION [PASS 2/2]
clean
echo DELETING POSTSCRIPT FILES
delete_postscript_files "."
echo BUILD COMPLETE.