#!/usr/bin/bash
touch .working
echo GENERATE PYDOC
pydoc pythinux > pythinux/man/pydoc
file_path="pythinux/man/pydoc"
if [ ! -f "$file_path" ]; then
    echo "Error: File '$file_path' does not exist."
    exit 1
fi
content=$(cat "$file_path")
new_content=$(echo "$content" | sed '/^FILE$/,/^$/d')
echo "$new_content" > "$file_path"
echo FORMAT USING BLACK
black pythinux.py -l 79
echo GENERATE FLAKE8RESULTS
echo '# This file was autogenerated using flake8.' > pythinux/man/lint
echo '# flake8 is a code linter that lists all violations of python standards.' >> pythinux/man/lint
flake8 pythinux.py --exclude E722 >> pythinux/man/lint
rm .working