#!/usr/bin/bash
delete_pyc() {
    find . -type f -name "*.pyc" -delete
}

# Function to delete __pycache__ folders
delete_pycache() {
    find . -type d -name "__pycache__" -exec rm -rf {} +
}
curr = $(date +%s)
touch .working
echo BUILD START.
echo RUNNING UNIT TEST
python unittest.py > pythinux/man/unittest
cp pythinux/man/unittest Documentation/Technical/unittest.txt
echo RESET INSTALLATION
python resetinstall.py
echo CLEANING UP INSTALLATION [PASS 1/2]
delete_pyc
delete_pycache
echo GENERATE PYDOC
pydoc pythinux > pythinux/man/pydoc
file_path="pythinux/man/pydoc"
if [ ! -f "$file_path" ]; then
    echo "Error: File '$file_path' does not exist."
    exit 1
fi
content=$(cat "$file_path")
new_content=$(echo "$content" | sed '/^FILE$/,/^$/d')
echo "$new_content" > "$file_path"
echo FORMAT USING BLACK
black pythinux.py -l 79
echo GENERATE LINT
echo '# This file was autogenerated using flake8.' > pythinux/man/lint
echo '# flake8 is a code linter that lists all violations of python standards.' >> pythinux/man/lint
flake8 pythinux.py --exclude E722 >> pythinux/man/lint
cp pythinux/man/lint Documentation/Technical/lint.txt
rm .working
echo CLEANING UP INSTALLATION [PASS 2/2]
delete_pyc
delete_pycache
echo BUILD COMPLETE.